[libraries]
kotlin-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21"
spotless-gradlePlugin = "com.diffplug.spotless:spotless-plugin-gradle:6.25.0"
ktlint-core = "com.pinterest.ktlint:ktlint-cli:1.3.1"
clikt = "com.github.ajalt.clikt:clikt:5.0.1"
