name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: assertk-migrator.zip
          path: build/distributions/*.zip
          if-no-files-found: error
